--CREATE USER SEMI5 IDENTIFIED BY SEMI5; 계정생성(관리자계정으로)
--GRANT CONNECT, RESOURCE TO SEMI5; 권한부여

-----------------------------------테이블----------------------------------------
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR2(32) NOT NULL UNIQUE,
    MEM_PWD VARCHAR2(32) NOT NULL,
    PHONE VARCHAR2(32) NOT NULL,
    EMAIL VARCHAR2(32) NOT NULL,
    STATUS VARCHAR2(2) DEFAULT 'Y'
);

DROP TABLE MUSIC;
CREATE TABLE MUSIC(
    MUS_NO NUMBER PRIMARY KEY,
    MUS_NAME VARCHAR2(100) NOT NULL,
    MUS_ART VARCHAR2(50) NOT NULL,
    MUS_GEN VARCHAR2(30),
    MUS_TIME VARCHAR2(10) NOT NULL,
    MUS_MV VARCHAR2(1000),
    STATUS VARCHAR2(2) DEFAULT 'Y'
);

DROP TABLE PLAYLIST;
CREATE TABLE PLAYLIST(
    PLA_NO NUMBER PRIMARY KEY,
    PLA_NAME VARCHAR2(100) NOT NULL,
    PLA_ART VARCHAR2(50) NOT NULL,
    PLA_GEN VARCHAR2(30),
    PLA_TIME VARCHAR2(10) NOT NULL,
    PLA_STATUS VARCHAR2(30) DEFAULT 'Y',
    MEM_NO NUMBER REFERENCES MEMBER(MEM_NO)
);

CREATE TABLE RECORD(
    PLA_NO NUMBER REFERENCES PLAYLIST(PLA_NO),
    MUS_NO NUMBER REFERENCES MUSIC(MUS_NO)
);

-----------------------------------시퀀스----------------------------------------
DROP SEQUENCE SEQ_MEM_NO;
CREATE SEQUENCE SEQ_MEM_NO
START WITH 2
INCREMENT BY 1
MAXVALUE 99
NOCYCLE
NOCACHE;

DROP SEQUENCE SEQ_PLA_NO;
CREATE SEQUENCE SEQ_PLA_NO
START WITH 1000
INCREMENT BY 1
MAXVALUE 1999
NOCYCLE
NOCACHE;

DROP SEQUENCE SEQ_MUS_NO;
CREATE SEQUENCE SEQ_MUS_NO
START WITH 100
INCREMENT BY 1
MAXVALUE 999
NOCYCLE
NOCACHE;

--------------------------더미데이터----------------------------------------------